/**
 * GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Run `npm run images` after changing anything in public/images.
 */
export interface ImageVariant { width: number; path: string }
export interface ImageEntry {
  original: string
  avif: ImageVariant[]
  webp: ImageVariant[]
}
export const IMAGE_VARIANTS: Record<string, ImageEntry> = {
  "images/1zPG7gUf.jpg": {
    "original": "images/1zPG7gUf.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/1zPG7gUf-640.avif"
      },
      {
        "width": 1280,
        "path": "images/1zPG7gUf-1280.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/1zPG7gUf-640.webp"
      },
      {
        "width": 1280,
        "path": "images/1zPG7gUf-1280.webp"
      }
    ]
  },
  "images/2d4ARPO7.jpg": {
    "original": "images/2d4ARPO7.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/2d4ARPO7-640.avif"
      },
      {
        "width": 1280,
        "path": "images/2d4ARPO7-1280.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/2d4ARPO7-640.webp"
      },
      {
        "width": 1280,
        "path": "images/2d4ARPO7-1280.webp"
      }
    ]
  },
  "images/6q8ePNfC.jpg": {
    "original": "images/6q8ePNfC.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/6q8ePNfC-640.avif"
      },
      {
        "width": 960,
        "path": "images/6q8ePNfC-960.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/6q8ePNfC-640.webp"
      },
      {
        "width": 960,
        "path": "images/6q8ePNfC-960.webp"
      }
    ]
  },
  "images/7zAFpr4L.jpg": {
    "original": "images/7zAFpr4L.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/7zAFpr4L-640.avif"
      },
      {
        "width": 960,
        "path": "images/7zAFpr4L-960.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/7zAFpr4L-640.webp"
      },
      {
        "width": 960,
        "path": "images/7zAFpr4L-960.webp"
      }
    ]
  },
  "images/GAVTNz9i.jpg": {
    "original": "images/GAVTNz9i.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/GAVTNz9i-640.avif"
      },
      {
        "width": 960,
        "path": "images/GAVTNz9i-960.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/GAVTNz9i-640.webp"
      },
      {
        "width": 960,
        "path": "images/GAVTNz9i-960.webp"
      }
    ]
  },
  "images/NuaaMhmi.jpg": {
    "original": "images/NuaaMhmi.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/NuaaMhmi-640.avif"
      },
      {
        "width": 1280,
        "path": "images/NuaaMhmi-1280.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/NuaaMhmi-640.webp"
      },
      {
        "width": 1280,
        "path": "images/NuaaMhmi-1280.webp"
      }
    ]
  },
  "images/RvTIVVo4.jpg": {
    "original": "images/RvTIVVo4.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/RvTIVVo4-640.avif"
      },
      {
        "width": 1280,
        "path": "images/RvTIVVo4-1280.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/RvTIVVo4-640.webp"
      },
      {
        "width": 1280,
        "path": "images/RvTIVVo4-1280.webp"
      }
    ]
  },
  "images/a63yCS4d.jpg": {
    "original": "images/a63yCS4d.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/a63yCS4d-640.avif"
      },
      {
        "width": 960,
        "path": "images/a63yCS4d-960.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/a63yCS4d-640.webp"
      },
      {
        "width": 960,
        "path": "images/a63yCS4d-960.webp"
      }
    ]
  },
  "images/cy64_SPi.jpg": {
    "original": "images/cy64_SPi.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/cy64_SPi-640.avif"
      },
      {
        "width": 736,
        "path": "images/cy64_SPi-736.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/cy64_SPi-640.webp"
      },
      {
        "width": 736,
        "path": "images/cy64_SPi-736.webp"
      }
    ]
  },
  "images/iH_ZprKY.jpg": {
    "original": "images/iH_ZprKY.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/iH_ZprKY-640.avif"
      },
      {
        "width": 960,
        "path": "images/iH_ZprKY-960.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/iH_ZprKY-640.webp"
      },
      {
        "width": 960,
        "path": "images/iH_ZprKY-960.webp"
      }
    ]
  },
  "images/jjLtVscv.jpg": {
    "original": "images/jjLtVscv.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/jjLtVscv-640.avif"
      },
      {
        "width": 960,
        "path": "images/jjLtVscv-960.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/jjLtVscv-640.webp"
      },
      {
        "width": 960,
        "path": "images/jjLtVscv-960.webp"
      }
    ]
  },
  "images/ne7gPXXV.jpg": {
    "original": "images/ne7gPXXV.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/ne7gPXXV-640.avif"
      },
      {
        "width": 1280,
        "path": "images/ne7gPXXV-1280.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/ne7gPXXV-640.webp"
      },
      {
        "width": 1280,
        "path": "images/ne7gPXXV-1280.webp"
      }
    ]
  },
  "images/wx_ojFvg.jpg": {
    "original": "images/wx_ojFvg.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/wx_ojFvg-640.avif"
      },
      {
        "width": 960,
        "path": "images/wx_ojFvg-960.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/wx_ojFvg-640.webp"
      },
      {
        "width": 960,
        "path": "images/wx_ojFvg-960.webp"
      }
    ]
  },
  "images/yBrcK6xm.jpg": {
    "original": "images/yBrcK6xm.jpg",
    "avif": [
      {
        "width": 640,
        "path": "images/yBrcK6xm-640.avif"
      },
      {
        "width": 1280,
        "path": "images/yBrcK6xm-1280.avif"
      }
    ],
    "webp": [
      {
        "width": 640,
        "path": "images/yBrcK6xm-640.webp"
      },
      {
        "width": 1280,
        "path": "images/yBrcK6xm-1280.webp"
      }
    ]
  }
}
